POST http://localhost:12000/api/addresses
Content-Type: application/json

{
  "country": "FR",
  "zipCode": "65332",
  "street": "20 rue du bonheur",
  "city": "Super City",
  "type": "none",
  "user": 1
}

###

GET http://localhost:12000/api/addresses?limit=10&orderBy=street&direction=DESC&user=1

###

PATCH http://localhost:12000/api/addresses/53
Content-Type: application/json

{
  "street": "53 rue des jardins"
}

###

GET http://localhost:12000/api/addresses/2

###

DELETE http://localhost:12000/api/addresses/53
