POST http://localhost:12000/api/addresses
Content-Type: application/json

{
  "country": "FR",
  "zipCode": "65332",
  "street": "20 rue du bonheur",
  "city": "Super City",
  "type": "none",
  "user": 1
}
