POST http://localhost:12000/api/token
Content-Type: application/json

{
  "username": "test@mail.com",
  "password": "test"
}

###

POST http://localhost:12000/api/addresses
Content-Type: application/json

{
  "country": "FR",
  "zipCode": "65332",
  "street": "20 rue du bonheur",
  "city": "Super City",
  "type": "none",
  "user": 1
}

###

GET http://localhost:12000/api/addresses?limit=10&orderBy=street&direction=DESC&user=1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2Njk3MjYzMTYsImV4cCI6MTY2OTcyOTkxNiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidGVzdEBtYWlsLmNvbSJ9.D1rrEVV2DzmVh1IcfMM1cfT8-WZK2HPOk5QVic-bXqQbeerip6Go2jhZjd4SxgKyfOjkxPwZuiG3LQCi2MWxZT_k_h55Ge-0co4F5wjYSrKLsYIo31LWoC4wgf3qn0x_j9C7zKHNuB804GkQ6vpusp5bT5kD2UfMWgogJt_9tUb2kGnmTbKZ0rlLheOQbhR9tPeMoFxCfhHB1lZz6H8Ebn8qPkjZUklOIHBnFSJTMLG2iSbfyCHXs9SLg26G_z59ABapHZpVmunkOV9QucwRNgH_Ozd0OzJD3WyDjuDwFmY6Yt29ZWUrQkAdpnwScIiwCsB22yK3qjxBuVeB6sov5w

###

PATCH http://localhost:12000/api/addresses/53
Content-Type: application/json

{
  "street": "53 rue des jardins"
}

###

GET http://localhost:12000/api/addresses/2

###

DELETE http://localhost:12000/api/addresses/53
