version: "3"

services:
  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - ${MYSQL_PORT}:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql

  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    restart: always
    depends_on:
      - mysql
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/app
    command: "symfony server:start --port=${APP_PORT}"

